### ISSUE TITLE
EVO 1.4.10 missing "lock" icons in document tree

### ISSUE THREAD

**Issue by ArnoNymeier** [evolution-cms/evolution#1312]
Hello,
after the update to EVO 1.4.10 the "lock" icons (displayed when the folder / files were restricted) are missing in the tree.

is there a fix for that?
Thanks

**Comment by bossloper** [comment]
yes it is fixed for the next release. Fix is here: https://github.com/evolution-cms/evolution/commit/29f80ce9a83407f1eab6c61cd82297902b39c117

**Comment by ArnoNymeier** [comment]
Hi bossloper,
thanks for the hint.
I have replaced the code line but the icons are still not displayed.
The problem is the "font" definition.
Replacing `font-family: 'Font Awesome 5 Free';` with `font-family: FontAwesome;` all works well.

**Comment by bossloper** [comment]
That is the old Fontawsome font 1.4.10 is migrating to Fontawsome5.
You need to put the fix in place, then resave the manager configuration to regenerate the manager css.
Then you may also need to force a browser refresh Ctrl/F5.

**Comment by ArnoNymeier** [comment]
OK, i will check it. Thanks
