### ISSUE TITLE
Plugin parameters are lost after update to the new version

### ISSUE THREAD

**Issue by Pathologic** [evolution-cms/evolution#65]
https://github.com/dmi3yy/modx.evo.custom/issues/501 is not fixed completely. Now parameters are kept only when update to the same version, but expected behaviour is to keep parameters in all cases.

**Comment by dmi3yy** [comment]
fixed https://github.com/evolution-cms/evolution/commit/c0702676bec92db5777daa4ea80ed088eb03bcc3

**Comment by Nicola1971** [comment]
i still have this issue updating 1.3.3 to 1.3.4 all plugin properties lost in update

**Comment by dmi3yy** [comment]
yes i fix this after 1.3.4 and will work from 1.3.5 version ) 

need fix all bugs in ditto noow not work filters ( and after that  release 1.3.5
