### ISSUE TITLE
Login form style Settings

### ISSUE THREAD

**Issue by Nicola1971** [evolution-cms/evolution#800]
A small improvement to the new login options, to fit any kind of image background and any dark customer logos:

![login_style](https://user-images.githubusercontent.com/7342798/44848898-ab8c5380-ac58-11e8-87fe-5d04c967a7e4.png)
![login_light](https://user-images.githubusercontent.com/7342798/44848914-b47d2500-ac58-11e8-9b66-11d0f9ae0738.png)

![loginstdark](https://user-images.githubusercontent.com/7342798/44849056-2ce3e600-ac59-11e8-80bb-95ca3686e560.png)
![login_dark](https://user-images.githubusercontent.com/7342798/44849060-2f464000-ac59-11e8-9ec3-c2fdb967ab48.png)

**Comment by 64j** [comment]
And yellow checkbox )

**Comment by pmfx** [comment]
Option for a light form theme makes sense, but I would make it less transparent. opacity: 0.85 or 0.9. 
Or even maybe full white.

Opacity 0.9:

![2018-08-30-14-11-50](https://user-images.githubusercontent.com/10888055/44850861-dd081d80-ac5e-11e8-82db-ffbfc72d2bbb.jpg)

Full white:

![2018-08-30-14-16-01](https://user-images.githubusercontent.com/10888055/44851023-4ee06700-ac5f-11e8-9bf5-4b74a14a2bd2.jpg)

**Comment by Nicola1971** [comment]
0.85 or 0.9 is ok for me.

In my Flat theme i've added a range input 😄 
![download1 2](https://user-images.githubusercontent.com/7342798/44863345-27989280-ac7d-11e8-82fb-2f851bd4ad49.png)

**Comment by risingisland** [comment]
Light login fields are too light, difficult to read...
![my evolution site evolution cms manager login](https://user-images.githubusercontent.com/6113504/46205065-55720500-c317-11e8-8d16-d52826f460ab.png)

**Comment by Nicola1971** [comment]
@risingisland 
fixed - forgot to add some styles from my dev
![screenshot-localhost-2018 09 28-13-17-28](https://user-images.githubusercontent.com/7342798/46205446-e8fc0380-c320-11e8-9864-fff52c8036fb.png)

**Comment by risingisland** [comment]
Sorry @Nicola1971 but it is still showing up as white.
Looks like it has to do with these two lines:
https://github.com/evolution-cms/evolution/blob/128e35b88f072824fc73be6ff13680b05dde3859/manager/media/style/default/login.tpl#L329-L330

**Comment by Nicola1971** [comment]
@risingisland on Firefox? 
Sorry not checked on FF - now fixed ;)

**Comment by risingisland** [comment]
Sorry, but I am trying it with both FF and Chrome, and no change.
Also, you seem to have added an extra file:
 evolution/manager/media/style/login.tpl

**Comment by Nicola1971** [comment]
upload to the wrong location :( - fixed
ok, for today it's better that I stop :)

**Comment by risingisland** [comment]
Ha, OK. No worries. :)
When you get a chance...
https://github.com/evolution-cms/evolution/blob/5abf6da336c3ebc2cf4dfecd3786e05dc88f450f/manager/media/style/default/login.tpl#L168
Maybe change to: `background-color: rgba(255, 255, 0, 0.3)!important;`

**Comment by risingisland** [comment]
Then you should upgrade :stuck_out_tongue_winking_eye:
Change transparency to whatever you see fit, but change the white to yellow or other.

**Comment by fourroses666** [comment]
or add a border arround the input

**Comment by Nicola1971** [comment]
![screenshot 2018-09-29 13 51 53](https://user-images.githubusercontent.com/7342798/46245503-e23bc200-c3ee-11e8-9b6f-932a14b403f9.png)

**Comment by pmfx** [comment]
Um, @Nicola1971 why inputs are yellow on your screenshots? Is it CSS or browser style? 
I think https://github.com/evolution-cms/evolution/issues/800#issuecomment-417298531 was OK. Adding light borders to inputs is OK too.

**Comment by pmfx** [comment]
Don't go yellow ;)
There is a yellow input background in Chrome only if there is saved form data for autofill. To override it in Chrome, you can try something like this:
```
/* remove the yellow background color on input fields */
input:-webkit-autofill {
  -webkit-box-shadow: inset 0 0 0px 9999px white;
}
```

**Comment by Nicola1971** [comment]
Thanks @pmfx , works but don't want to override browser styles.

switched back to white input  
Firefox light loginbox
![screenshot 2018-09-29 14 51 08](https://user-images.githubusercontent.com/7342798/46245998-92152d80-c3f7-11e8-81bf-d40309e4bd98.png)
